preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  normalize: per_feature
  window_size: 0.02
  sample_rate: 16000
  window_stride: 0.01
  window: hann
  features: 64
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  stft_conv: false
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  rect_freq: 50
  rect_masks: 5
  rect_time: 120
encoder:
  _target_: nemo.collections.asr.modules.ConvASREncoder
  feat_in: 64
  activation: relu
  conv_mask: true
  jasper:
  - filters: 256
    repeat: 1
    kernel:
    - 33
    stride:
    - 2
    dilation:
    - 1
    dropout: 0.0
    residual: false
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 33
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 256
    repeat: 5
    kernel:
    - 39
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 51
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 63
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 5
    kernel:
    - 75
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: true
    separable: true
  - filters: 512
    repeat: 1
    kernel:
    - 87
    stride:
    - 1
    dilation:
    - 2
    dropout: 0.0
    residual: false
    separable: true
  - filters: 1024
    repeat: 1
    kernel:
    - 1
    stride:
    - 1
    dilation:
    - 1
    dropout: 0.0
    residual: false
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 1024
  num_classes: 34
  vocabulary:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
optim:
  name: novograd
  lr: 0.0012
  betas:
  - 0.8
  - 0.5
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    warmup_steps: 500
    warmup_ratio: null
    min_lr: 0.0
    last_epoch: -1
target: nemo.collections.asr.models.ctc_models.EncDecCTCModel
train_ds:
  manifest_filepath: /raid/noneval.json
  sample_rate: 16000
  labels:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
  batch_size: 16
  trim_silence: true
  max_duration: 16.7
  shuffle: true
  is_tarred: false
  tarred_audio_filepaths: null
  num_workers: 8
  pin_memory: true
validation_ds:
  manifest_filepath: /raid/dev.json
  sample_rate: 16000
  labels:
  - ' '
  - а
  - б
  - в
  - г
  - д
  - е
  - ё
  - ж
  - з
  - и
  - й
  - к
  - л
  - м
  - н
  - о
  - п
  - р
  - с
  - т
  - у
  - ф
  - х
  - ц
  - ч
  - ш
  - щ
  - ъ
  - ы
  - ь
  - э
  - ю
  - я
  batch_size: 32
  shuffle: false
  num_workers: 8
  pin_memory: true
nemo_version: 1.21.0
decoding:
  strategy: greedy
  preserve_alignments: null
  compute_timestamps: null
  word_seperator: ' '
  ctc_timestamp_type: all
  batch_dim_index: 0
  greedy:
    preserve_alignments: false
    compute_timestamps: false
    preserve_frame_confidence: false
    confidence_measure_cfg:
      name: entropy
      entropy_type: tsallis
      alpha: 0.33
      entropy_norm: exp
      temperature: DEPRECATED
    confidence_method_cfg: DEPRECATED
  beam:
    beam_size: 4
    search_type: default
    preserve_alignments: false
    compute_timestamps: false
    return_best_hypothesis: true
    beam_alpha: 1.0
    beam_beta: 0.0
    kenlm_path: null
    flashlight_cfg:
      lexicon_path: null
      boost_path: null
      beam_size_token: 16
      beam_threshold: 20.0
      unk_weight: -.inf
      sil_weight: 0.0
    pyctcdecode_cfg:
      beam_prune_logp: -10.0
      token_min_logp: -5.0
      prune_history: false
      hotwords: null
      hotword_weight: 10.0
  confidence_cfg:
    preserve_frame_confidence: false
    preserve_token_confidence: false
    preserve_word_confidence: false
    exclude_blank: true
    aggregation: min
    measure_cfg:
      name: entropy
      entropy_type: tsallis
      alpha: 0.33
      entropy_norm: exp
      temperature: DEPRECATED
    method_cfg: DEPRECATED
  temperature: 1.0
